/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Все предстоящие встречи всех типов событий, отсортированы по start. */
        get: operations["BookingsAdmin_list"];
        put?: never;
        /** @description Создать бронь на выбранный слот. */
        post: operations["BookingsCreate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список видов брони (title, description, durationMinutes). */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать тип события. */
        post: operations["EventTypesAdmin_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Детали одного типа события. */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты для типа события в окне 14 дней.
         *     Учитывает глобальную занятость и помещаемость N смежных ячеек.
         */
        get: operations["EventTypes_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Профиль владельца для шапки публичной страницы. */
        get: operations["OwnerApi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Оформленная запись на встречу. */
        Booking: {
            /** @description Уникальный идентификатор брони (UUID), назначается сервером. */
            readonly id: string;
            /** @description Идентификатор типа события, к которому относится бронь. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало встречи (ISO 8601, UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи = start + durationMinutes, вычисляется сервером (ISO 8601, UTC).
             */
            readonly end: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя.
             */
            guestEmail: string;
            /** @description Необязательная тема/комментарий к встрече. */
            comment?: string;
            /**
             * Format: date-time
             * @description Момент создания брони, назначается сервером (ISO 8601, UTC).
             */
            readonly createdAt: string;
        };
        /** @description Тело запроса на создание брони (end, id, createdAt вычисляет сервер). */
        BookingCreate: {
            /** @description Тип события, на который записывается гость. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Выбранное начало слота (ISO 8601, UTC), должно быть на 30-мин сетке.
             */
            start: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            comment?: string;
        };
        /** @description Тип события (вид встречи), которым управляет владелец. */
        EventType: {
            /** @description Уникальный идентификатор (UUID), назначается сервером. */
            readonly id: string;
            /** @description Короткое название типа встречи. */
            title: string;
            /** @description Описание типа встречи для гостя. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             *     Должна быть кратна 30 и не меньше 30 (одна или несколько 30-мин ячеек).
             */
            durationMinutes: number;
        };
        /** @description Тело запроса на создание типа события (id назначает сервер). */
        EventTypeCreate: {
            title: string;
            description: string;
            /**
             * Format: int32
             * @description Кратно 30, минимум 30.
             */
            durationMinutes: number;
        };
        /** @description Ресурс не найден (например, неизвестный eventTypeId). */
        NotFoundError: {
            /** @enum {string} */
            code: "not_found";
            message: string;
        };
        /** @description Профиль владельца календаря (единственный, только чтение). */
        Owner: {
            /** @description Отображаемое имя владельца — «Записаться на созвон к …». */
            name: string;
            /** @description IANA-таймзона владельца, по ней считаются рабочие часы (напр. "Europe/Moscow"). */
            timezone: string;
        };
        /**
         * @description Свободный слот — вычисляемый интервал, в БД не хранится.
         *     Возвращается для конкретного типа события: начиная с `start` подряд свободны
         *     N = durationMinutes/30 ячеек, всё внутри рабочих часов и окна 14 дней.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, выровнено по 30-минутной сетке (ISO 8601, UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота = start + durationMinutes типа события (ISO 8601, UTC).
             */
            end: string;
        };
        /** @description Слот уже занят / пересекается с существующей бронью (глобальное правило). */
        SlotTakenError: {
            /** @enum {string} */
            code: "slot_taken";
            message: string;
        };
        /**
         * @description Ошибка валидации: start не на 30-мин сетке, вне рабочих часов, вне окна 14 дней,
         *     durationMinutes не кратно 30, невалидный email и т. п.
         */
        ValidationError: {
            /** @enum {string} */
            code: "validation_error";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BookingsAdmin_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    BookingsCreate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Ресурс не найден (например, неизвестный eventTypeId). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description Слот уже занят / пересекается с существующей бронью (глобальное правило). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotTakenError"];
                };
            };
            /**
             * @description Ошибка валидации: start не на 30-мин сетке, вне рабочих часов, вне окна 14 дней,
             *     durationMinutes не кратно 30, невалидный email и т. п.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypesAdmin_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /**
             * @description Ошибка валидации: start не на 30-мин сетке, вне рабочих часов, вне окна 14 дней,
             *     durationMinutes не кратно 30, невалидный email и т. п.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден (например, неизвестный eventTypeId). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypes_slots: {
        parameters: {
            query?: {
                /** @description Начало окна (по умолчанию — текущий момент). */
                from?: string;
                /** @description Размер окна в днях (по умолчанию 14). */
                days?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Ресурс не найден (например, неизвестный eventTypeId). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerApi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
